### PR TITLE
feat(item): emit event on selection

### PR DESCRIPTION
**Pull request by jornetsimon**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the new behavior?
`ItemDirective.selected` emits an object which holds a KeyboardEvent or PointerEvent.
This is useful for further processing based on the event that triggered the item selection.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by jornetsimon** [comment]
Skipped the unit test because it's broken atm
CleanShot 2023-04-14 at 13 40 10@2x

**Comment by shhdharmen** [comment]
Change target branch to `beta`

**Comment by va-stefanek** [comment]
Maybe emit should happen only when there is an observer?

**Pull request merged**
