### PR TITLE
feat: upgrade to angular version 16

### LINKED ISSUE #7: Upgrade to Angular 16
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Depends on version 15.x of Angular

## Expected behavior

Depends on version 16.x of Angular

## What is the motivation / use case for changing the behavior?

I'd like to use this is a new component library that I am building! The project uses Angular 16 and up
so I was wondering if it is possible to upgrade the dependencies of this project!

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

Thanks for your incredible work and I am happy to contribute and give it a try if you want me to!

### PR DESCRIPTION
**Pull request by goetzrobin**
Upgrades angular and all dependencies necessary to version 16.

Closes #7

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

V15 of Angular is used

Issue Number: #7 

## What is the new behavior?

V16 of Angular is used

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

Just wanted to offer this as a PR, too! Thanks for your work on this! I am very excited to use it 👍

### CODE REVIEW

**Review by shhdharmen — CHANGES_REQUESTED** [review]
This is a breaking change. Please fix your commit msg. Also, change target branch to `beta`.

**Comment by goetzrobin** [comment]
> Commit msg is still not right. Please run npm run commit after staging your changes and make sure to select breaking change.

Thanks for pointing that out @shhdharmen! I was not aware of that command. 

Since this change was a while ago, I wanted to check in with you and ask to which version you'd want to update and how restrictive you want to version to be?

Thanks for your patience with this! It's my first time committing to an ngneat repository so there's some things that I have missed and I am guilty of not reading the contributing guidelines before I started... Sorry about that!

**Comment by jkuri** [comment]
hi @shhdharmen, can you please merge this and publish to npm, please? currently there is no way to use this with Angular v16.

**Comment by shhdharmen** [comment]
I will check in the weekend.

Thanks,
Dharmen Shah

**Pull request closed without merging**
